services:
  circuitbreaker:
    image: ${DOCKER_REGISTRY-}circuitbreaker
    build:
      context: .
      dockerfile: CircuitBreaker/Dockerfile
    ports:
     -   7076:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80 
      # Eureka client
      EUREKA__CLIENT__SERVICEURL: http://host.docker.internal:8761/eureka/
      EUREKA__CLIENT__SHOULDFETCHREGISTRY: "true"
      EUREKA__CLIENT__SHOULDREGISTERWITHEUREKA: "true"

      # Override what gets registered
      EUREKA__INSTANCE__APPNAME: CB-COMMON
      EUREKA__INSTANCE__HOSTNAME: cb-common       # force Eureka to use "localhost"
      EUREKA__INSTANCE__NONSECUREPORT: "80"      # advertise the HOST port
      EUREKA__INSTANCE__PREFERIPADDRESS: "false"
      # make it unique if you scale
      EUREKA__INSTANCE__INSTANCEID: "cb-common-localhost:80"

      # optional but recommended so Eureka health links work from host:
      EUREKA__INSTANCE__STATUSPAGEURL: "http://localhost:7076/health"
      EUREKA__INSTANCE__HEALTHCHECKURL: "http://localhost:7076/health"
    networks:
      boeingnetwork:
        aliases: [boeing-common] 
networks:
  boeingnetwork:
    external: true 
